### ISSUE TITLE
Message « unknown option: --no-scrollbar » 

### ISSUE THREAD

**Issue by ronron22** [archusXIV/mpv-playlists-manager#1]
En recherchant avec le mot « chats » j'obtiens le message suivant

```bash
Tip: In the fzf menu press Tab on the desired Video titles,
 then press Enter to confirm. Press Escape to cancel.
 (note that multi-selection is supported)

 Search for youtube Video (no quotes): chats
unknown option: --no-scrollbar


                                            ::SEARCH ONLINE VIDEO OPTIONS::
                                 ┌──────────────────────────────────────────────────┐
                                 │   1) Fzf Youtube search   4) Ytfzf PeerTube      │
                                 │   2) Ytfzf Youtube        5) Back to Video menu  │
                                 │   3) Ytfzf Odysee         6) Back to main menu   │
                                 └──────────────────────────────────────────────────┘
                                                   Select an item
```

**Comment by archusXIV** [comment]
Salut tonio, je ne comprend pas ton screenshot, le menu SEARCH ONLINE VIDEO OPTIONS est-il encore présent quand le message Tip:....... apparait?
Ok c'est fzf qui te parle mais je n'arrive pas à recréer cette "erreur"
Regarde le code à la ligne 53: https://github.com/archusXIV/mpv-playlists-manager/blob/main/lib/_SearchYoutubeWithFzf#L53

Est-ce que celà se reproduit à chaque fois?

________________________________________
De : Ronron ***@***.***>
Envoyé : vendredi 7 juin 2024 21:59
À : archusXIV/mpv-playlists-manager
Cc : Subscribed
Objet : [archusXIV/mpv-playlists-manager] Message « unknown option: --no-scrollbar »  (Issue #1)

En recherchant avec le mot « chats » j'obtiens le message suivant

Tip: In the fzf menu press Tab on the desired Video titles,
 then press Enter to confirm. Press Escape to cancel.
 (note that multi-selection is supported)

 Search for youtube Video (no quotes): chats
unknown option: --no-scrollbar


                                            ::SEARCH ONLINE VIDEO OPTIONS::
                                 ┌──────────────────────────────────────────────────┐
                                 │   1) Fzf Youtube search   4) Ytfzf PeerTube      │
                                 │   2) Ytfzf Youtube        5) Back to Video menu  │
                                 │   3) Ytfzf Odysee         6) Back to main menu   │
                                 └──────────────────────────────────────────────────┘
                                                   Select an item

**Comment by ronron22** [comment]
Hello, 

Sous Ubuntu Jammy, fzf en version 0.29 (devel) ne semble pas supporter cette option.
Sur le git du projet, la branch main l'implémente (version 0.53.0).

**Comment by archusXIV** [comment]
Tu as corrigé la fonction chez toi et cela fonctionne?
[man page](https://manpages.debian.org/bookworm/fzf/fzf.1.en.html#no-scrollbar)
[debian package](https://packages.debian.org/bookworm/fzf)
Debian stable l'option est supportée.
Fzf est un paquet optionnel pour mpm alors je ne pense pas rétrograder, si celà fonctionne avec ytfzf alors tant mieux pour Ubuntu 22.04.
Laisses-moi savoir ce que tu en penses.

**Comment by archusXIV** [comment]
Debian stable l'option est supportée.
